# Generated by Django 6.0.7 on 2026-07-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('streak', 'Streak'), ('learning', 'Learning'), ('practice', 'Practice'), ('test', 'Test'), ('special', 'Special')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('requirement_type', models.CharField(max_length=50)),
                ('requirement_value', models.PositiveIntegerField()),
                ('color', models.CharField(default='#a0a0a0', max_length=7)),
            ],
            options={
                'ordering': ['rarity', 'category', 'name'],
                'indexes': [models.Index(fields=['category'], name='progress_ba_categor_208580_idx'), models.Index(fields=['rarity'], name='progress_ba_rarity_a5b9c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='progress.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'earned_at'], name='progress_us_user_id_84cd9b_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_xp', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['current_level'], name='progress_us_current_97241a_idx'), models.Index(fields=['total_xp_earned'], name='progress_us_total_x_2d0dd8_idx')],
            },
        ),
    ]
