# Generated by Django 6.0.7 on 2026-08-02 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_badge_userbadge_userlevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=200)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('source_object_type', models.CharField(blank=True, max_length=50)),
                ('source_object_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='progress_xp_user_id_1bf5ea_idx'), models.Index(fields=['event_type'], name='progress_xp_event_t_baafd5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_user_xp_idempotency_key')],
            },
        ),
    ]
