# Generated by Django 6.0.7 on 2026-07-26 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('num_questions', models.PositiveIntegerField(default=10)),
                ('time_limit_minutes', models.PositiveIntegerField(default=10)),
                ('questions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='created', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['user'], name='assessments_user_id_a5176f_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status'], name='assessments_status_e956c3_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['topic'], name='assessments_topic_50ce8f_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test'], name='assessments_test_id_581677_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user'], name='assessments_user_id_fabc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['completed_at'], name='assessments_complet_bd7b59_idx'),
        ),
    ]
