# Generated by Django 6.0.7 on 2026-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
