# Generated by Django 6.0.8 on 2026-08-22 04:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=60)),
                ('difficulty_band', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('default_half_life_days', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain', 'code'],
                'indexes': [models.Index(fields=['domain', 'is_active'], name='intelligenc_domain_4af343_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code', '-version'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='unique_skill_pack_version')],
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('assessment_answer', 'Assessment answer'), ('challenge_answer', 'Challenge answer'), ('coding_attempt', 'Coding attempt'), ('lesson_complete', 'Lesson completion'), ('ai_review', 'AI review'), ('diagnostic_answer', 'Diagnostic answer'), ('project_rubric', 'Project rubric'), ('teach_back', 'Tutor teach-back'), ('self_report', 'Self report')], max_length=40)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('outcome', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('difficulty', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('evidence_weight', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('10.000'))])),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_events', to='intelligence.skill')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['user', 'skill', 'occurred_at'], name='intelligenc_user_id_fdf5e6_idx'), models.Index(fields=['user', 'event_type', 'occurred_at'], name='intelligenc_user_id_9bc0c5_idx'), models.Index(fields=['source_type', 'source_id'], name='intelligenc_source__4fae6d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_user_learning_event_key')],
            },
        ),
        migrations.CreateModel(
            name='SkillPackMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('is_core', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='intelligence.skillpack')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_memberships', to='intelligence.skill')),
            ],
            options={
                'ordering': ['pack', 'order'],
                'constraints': [models.UniqueConstraint(fields=('pack', 'skill'), name='unique_skill_per_pack'), models.UniqueConstraint(fields=('pack', 'order'), name='unique_skill_order_per_pack')],
            },
        ),
        migrations.CreateModel(
            name='SkillPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_mastery', models.DecimalField(decimal_places=4, default=Decimal('0.6000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('minimum_confidence', models.DecimalField(decimal_places=4, default=Decimal('0.4000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('strength', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='intelligence.skill')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='intelligence.skill')),
            ],
            options={
                'ordering': ['dependent__code', 'prerequisite__code'],
                'constraints': [models.UniqueConstraint(fields=('prerequisite', 'dependent'), name='unique_skill_prerequisite'), models.CheckConstraint(condition=models.Q(('prerequisite', models.F('dependent')), _negated=True), name='skill_cannot_require_itself')],
            },
        ),
        migrations.CreateModel(
            name='SkillState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('freshness', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('total_evidence_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('misconception_codes', models.JSONField(blank=True, default=list)),
                ('algorithm_version', models.CharField(default='weighted-evidence-v1', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='intelligence.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'skill__code'],
                'indexes': [models.Index(fields=['user', 'mastery'], name='intelligenc_user_id_388a98_idx'), models.Index(fields=['user', 'freshness'], name='intelligenc_user_id_b0e979_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_skill_state')],
            },
        ),
    ]
