# Generated by Django 6.0.8 on 2026-08-22 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('routing', 'Routing diagnostic'), ('goal', 'Goal-specific diagnostic')], max_length=20)),
                ('diagnostic_code', models.CharField(max_length=100)),
                ('question_set_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_attempts', to='intelligence.skillpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('selected_option', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='intelligence.diagnosticattempt')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_responses', to='intelligence.skill')),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
        migrations.CreateModel(
            name='LearnerIntelligenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_goal', models.CharField(choices=[('semester', 'Semester learning'), ('placement', 'Placement and interview preparation'), ('project', 'Project building'), ('machine_learning', 'Machine learning'), ('fullstack', 'Full-stack development'), ('custom', 'Custom goal')], max_length=40)),
                ('custom_goal', models.CharField(blank=True, max_length=300)),
                ('routing_diagnostic_completed_at', models.DateTimeField(blank=True, null=True)),
                ('goal_diagnostic_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_profiles', to='intelligence.skillpack')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='diagnosticattempt',
            index=models.Index(fields=['user', 'stage', 'status'], name='intelligenc_user_id_f34b5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question_id'), name='unique_diagnostic_response'),
        ),
    ]
