# Generated by Django 6.0.8 on 2026-08-22 09:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_diagnosticattempt_diagnosticresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(choices=[('diagnostic', 'Diagnostic'), ('learn', 'Learn'), ('practice', 'Practice'), ('remediation', 'Remediation'), ('retention', 'Retention'), ('project', 'Project'), ('stretch', 'Stretch')], max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('active', 'Active'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('expired', 'Expired')], default='proposed', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1200)),
                ('rationale', models.JSONField(default=dict)),
                ('success_criteria', models.JSONField(default=dict)),
                ('expected_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)])),
                ('evidence_policy_version', models.CharField(default='weighted-evidence-v1', max_length=60)),
                ('recommendation_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('additional_skills', models.ManyToManyField(blank=True, related_name='supporting_missions', to='intelligence.skill')),
                ('primary_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_missions', to='intelligence.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='intelligenc_user_id_9de293_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recommendation_key'), name='unique_user_recommendation_key'), models.CheckConstraint(condition=models.Q(('expected_minutes__gte', 5), ('expected_minutes__lte', 240)), name='mission_expected_minutes_range')],
            },
        ),
    ]
