# Generated by Django 6.0.8 on 2026-08-22 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_mission'),
        ('learning', '0003_alter_roadmap_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='postponed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('active', 'Active'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('skipped', 'Skipped'), ('expired', 'Expired')], default='proposed', max_length=20),
        ),
        migrations.CreateModel(
            name='RoadmapRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('postponed', 'Postponed'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], max_length=20)),
                ('reason_code', models.CharField(choices=[('initial_skill_route', 'Initial skill route'), ('mission_proposal', 'Mission proposal'), ('restored_revision', 'Restored revision')], max_length=40)),
                ('summary', models.CharField(max_length=800)),
                ('input_state_version', models.CharField(max_length=64)),
                ('input_state_at', models.DateTimeField()),
                ('algorithm_version', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('postponed_until', models.DateTimeField(blank=True, null=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_revisions', to='intelligence.roadmaprevision')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_revisions', to='learning.roadmap')),
                ('trigger_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_revisions', to='intelligence.mission')),
            ],
            options={
                'ordering': ['roadmap', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('locked', 'Prerequisite locked'), ('ready', 'Ready'), ('active', 'Active'), ('complete', 'Complete'), ('skipped', 'Skipped')], max_length=20)),
                ('rationale', models.CharField(max_length=1000)),
                ('expected_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)])),
                ('is_user_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_nodes', to='intelligence.mission')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roadmap_nodes', to='intelligence.skill')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='intelligence.roadmaprevision')),
            ],
            options={
                'ordering': ['revision', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='roadmaprevision',
            index=models.Index(fields=['roadmap', 'status', 'revision_number'], name='intelligenc_roadmap_ce5943_idx'),
        ),
        migrations.AddConstraint(
            model_name='roadmaprevision',
            constraint=models.UniqueConstraint(fields=('roadmap', 'revision_number'), name='unique_roadmap_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='roadmaprevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('roadmap',), name='one_active_revision_per_roadmap'),
        ),
        migrations.AddConstraint(
            model_name='roadmaprevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'proposed')), fields=('roadmap',), name='one_proposed_revision_per_roadmap'),
        ),
        migrations.AddConstraint(
            model_name='roadmaprevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='roadmap_revision_number_positive'),
        ),
        migrations.AddIndex(
            model_name='roadmapnode',
            index=models.Index(fields=['revision', 'status', 'order'], name='intelligenc_revisio_5c298d_idx'),
        ),
        migrations.AddConstraint(
            model_name='roadmapnode',
            constraint=models.UniqueConstraint(fields=('revision', 'order'), name='unique_node_order_per_revision'),
        ),
        migrations.AddConstraint(
            model_name='roadmapnode',
            constraint=models.UniqueConstraint(fields=('revision', 'skill'), name='unique_skill_per_revision'),
        ),
        migrations.AddConstraint(
            model_name='roadmapnode',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='roadmap_node_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='roadmapnode',
            constraint=models.CheckConstraint(condition=models.Q(('expected_minutes__gte', 5), ('expected_minutes__lte', 240)), name='roadmap_node_expected_minutes_range'),
        ),
    ]
