# Generated by Django 6.0.8 on 2026-08-22 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0002_imageanalysis'),
        ('intelligence', '0004_mission_postponed_until_alter_mission_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helped', 'Helpful'), ('too_fast', 'Too fast'), ('too_detailed', 'Too detailed'), ('more_examples', 'More examples'), ('more_code', 'More code'), ('ask_me_questions', 'Ask me questions'), ('already_known', 'I already knew this')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_feedback', to='ai_tools.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['user', 'feedback_type', 'updated_at'], name='intelligenc_user_id_979c8d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'message'), name='unique_tutor_feedback_per_message')],
            },
        ),
        migrations.CreateModel(
            name='TutorMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('goal', 'Goal'), ('misconception', 'Misconception to revisit'), ('preference', 'Teaching preference'), ('project', 'Current project'), ('revisit', 'Topic to revisit'), ('session_summary', 'Session summary')], max_length=30)),
                ('content', models.TextField(max_length=600)),
                ('reason', models.CharField(max_length=300)),
                ('source_type', models.CharField(choices=[('explicit_user', 'Added by learner'), ('observed_feedback', 'Suggested from repeated feedback')], default='explicit_user', max_length=30)),
                ('source_key', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('user_confirmed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_memories', to='ai_tools.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_active', 'category'], name='intelligenc_user_id_95b672_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('user', 'source_key'), name='unique_user_tutor_memory_source'), models.UniqueConstraint(condition=models.Q(('category', 'session_summary')), fields=('user', 'chat_session'), name='unique_tutor_session_summary')],
            },
        ),
        migrations.CreateModel(
            name='TutorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_depth', models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], default='balanced', max_length=20)),
                ('teaching_mode', models.CharField(choices=[('direct', 'Direct explanation'), ('example_first', 'Example first'), ('socratic', 'Socratic questions'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('code_density', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('preferred_language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('hinglish', 'Hinglish'), ('marathi', 'Marathi')], default='english', max_length=20)),
                ('pace', models.CharField(choices=[('gentle', 'Gentle'), ('steady', 'Steady'), ('fast', 'Fast')], default='steady', max_length=20)),
                ('session_minutes', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('accessibility_preferences', models.JSONField(blank=True, default=dict)),
                ('learning_context_enabled', models.BooleanField(default=True)),
                ('observed_adaptation_enabled', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('session_minutes__gte', 10), ('session_minutes__lte', 120)), name='tutor_session_minutes_range')],
            },
        ),
    ]
