# Generated by Django 6.0.8 on 2026-08-23 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_tutorfeedback_tutormemory_tutorpreference'),
        ('learning', '0003_alter_roadmap_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('passport', 'Skill Passport'), ('roadmap', 'Roadmap')], max_length=20)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(default='CodeLabX learner', max_length=80)),
                ('include_evidence_counts', models.BooleanField(default=True)),
                ('include_completed_items', models.BooleanField(default=True)),
                ('snapshot', models.JSONField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('snapshot_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_shares', to='learning.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_learning_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'share_type', 'is_active'], name='intelligenc_user_id_469376_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('roadmap__isnull', True), ('share_type', 'passport')), models.Q(('roadmap__isnull', False), ('share_type', 'roadmap')), _connector='OR'), name='public_share_target_matches_type'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('share_type', 'passport')), fields=('user',), name='one_active_passport_share_per_user'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('share_type', 'roadmap')), fields=('user', 'roadmap'), name='one_active_roadmap_share_per_user')],
            },
        ),
    ]
