# Generated by Django 6.0.8 on 2026-08-23 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailpreference_weeklyreportdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=39)),
                ('github_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('public_repos', models.PositiveIntegerField(default=0)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('never', 'Not synchronized'), ('synced', 'Synchronized'), ('error', 'Refresh failed')], default='never', max_length=20)),
                ('last_error_code', models.CharField(blank=True, max_length=60)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('html_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('stargazers_count', models.PositiveIntegerField(default=0)),
                ('forks_count', models.PositiveIntegerField(default=0)),
                ('is_fork', models.BooleanField(default=False)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='accounts.githubconnection')),
            ],
            options={
                'ordering': ['-pushed_at', 'name'],
                'indexes': [models.Index(fields=['connection', '-pushed_at'], name='accounts_gi_connect_bc48f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'github_id'), name='unique_github_repo_snapshot')],
            },
        ),
    ]
