# Generated by Django 6.0.7 on 2026-07-28 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_analysis/%Y/%m/')),
                ('analysis_type', models.CharField(choices=[('general', 'General Analysis'), ('code', 'Code Explanation'), ('math', 'Math Problem'), ('handwritten', 'Handwritten Notes'), ('diagram', 'Diagram/Chart')], default='general', max_length=20)),
                ('user_question', models.TextField(blank=True, help_text='Optional question about the image')),
                ('ai_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
