# Generated by Django 6.0.7 on 2026-07-25 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('ML', 'Machine Learning'), ('DSA', 'Data Structures & Algorithms')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_days', models.PositiveIntegerField()),
                ('daily_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='learning.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['user'], name='learning_ro_user_id_fd5146_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['topic'], name='learning_ro_topic_83eb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['status'], name='learning_ro_status_9e092f_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['start_date', 'end_date'], name='learning_ro_start_d_700edc_idx'),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['roadmap'], name='learning_da_roadmap_3afbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['day_number'], name='learning_da_day_num_668636_idx'),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['order'], name='learning_da_order_946c22_idx'),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['is_completed'], name='learning_da_is_comp_004754_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('roadmap', 'day_number')},
        ),
    ]
