# Generated by Django 6.0.7 on 2026-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='ai_content',
            field=models.TextField(blank=True, help_text='AI generated theory content', null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='ai_content_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
