# Generated by Django 6.0.8 on 2026-08-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_day_ai_content_day_ai_content_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='topic',
            field=models.CharField(choices=[('ML', 'Machine Learning'), ('DSA', 'Data Structures & Algorithms'), ('FULLSTACK', 'Django & Full-Stack')], max_length=10),
        ),
    ]
