# Generated by Django 6.0.7 on 2026-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='evaluation_type',
            field=models.CharField(default='deterministic', max_length=30),
        ),
    ]
